[ERROR 2022-04-05 20:05:51,226] worker.py: 409  SystemExit was raised from the worker
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 595, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 453, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 490, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 497, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/home/haoranliao/anaconda3/envs/tf2.7/lib/python3.9/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/haoranliao/anaconda3/envs/tf2.7/lib/python3.9/site-packages/ray/tune/trainable.py", line 173, in train_buffered
    result = self.train()
  File "/home/haoranliao/anaconda3/envs/tf2.7/lib/python3.9/site-packages/ray/tune/trainable.py", line 232, in train
    result = self.step()
  File "/tmp/pycharm_project_948/uni_ttn/tf2.7/non_distributed_tunning/model.py", line 222, in step
    self.model.run_epoch(batch_size, grad_accumulation=config['data']['grad_accumulation'])
  File "/tmp/pycharm_project_948/uni_ttn/tf2.7/non_distributed_tunning/model.py", line 191, in run_epoch
    self.network.update(train_image_batch, train_label_batch, apply_grads=True, counter=counter)
  File "/tmp/pycharm_project_948/uni_ttn/tf2.7/non_distributed_tunning/network.py", line 91, in update
    loss = self.loss(input_batch, label_batch)
  File "/home/haoranliao/anaconda3/envs/tf2.7/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/home/haoranliao/anaconda3/envs/tf2.7/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 862, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/home/haoranliao/anaconda3/envs/tf2.7/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/home/haoranliao/anaconda3/envs/tf2.7/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 1926, in _call_flat
    flat_outputs = forward_function.call(
  File "/home/haoranliao/anaconda3/envs/tf2.7/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/home/haoranliao/anaconda3/envs/tf2.7/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
  File "/home/haoranliao/anaconda3/envs/tf2.7/lib/python3.9/site-packages/ray/worker.py", line 406, in sigterm_handler
    sys.exit(1)
SystemExit: 1
