[ERROR 2022-05-04 15:28:52,750] worker.py: 409  Exception raised in creation task: The actor died because of an error raised in its creation task, [36mray::MERA.__init__()[39m (pid=219303, ip=128.32.17.9)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/home/haoranliao/anaconda3/envs/tf2.7/lib/python3.9/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/haoranliao/anaconda3/envs/tf2.7/lib/python3.9/site-packages/ray/tune/trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/tmp/pycharm_project_948/mera/non_distributed_tunning/model.py", line 221, in setup
    self.model = Model(data_path, digits, val_split, deph_p, num_anc, config, tune_config)
  File "/tmp/pycharm_project_948/mera/non_distributed_tunning/model.py", line 94, in __init__
    train_data, val_data, test_data = data.get_data_file(
  File "/tmp/pycharm_project_948/mera/non_distributed_tunning/../../uni_ttn/tf2.7/data.py", line 156, in get_data_file
    (train_raw_im, train_raw_lab) = load_data(data_path + '_train')
  File "/tmp/pycharm_project_948/mera/non_distributed_tunning/../../uni_ttn/tf2.7/data.py", line 201, in load_data
    dest = open(path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/qc_whaley/dephased_ttn_project/mnist4by4/mnist4by4_train'
