[ERROR 2022-05-04 15:27:04,806] worker.py: 409  Exception raised in creation task: The actor died because of an error raised in its creation task, [36mray::MERA.__init__()[39m (pid=216582, ip=128.32.17.9)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/home/haoranliao/anaconda3/envs/tf2.7/lib/python3.9/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/haoranliao/anaconda3/envs/tf2.7/lib/python3.9/site-packages/ray/tune/trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/tmp/pycharm_project_948/mera/non_distributed_tunning/model.py", line 221, in setup
    self.model = Model(data_path, digits, val_split, deph_p, num_anc, config, tune_config)
  File "/tmp/pycharm_project_948/mera/non_distributed_tunning/model.py", line 93, in __init__
    assert data_im_size == [4, 4] and feature_dim == 2
AssertionError
