Failure # 1 (occurred at 2022-04-07_02-44-47)
Traceback (most recent call last):
  File "/home/qc_whaley/anaconda3/envs/tf2.6/lib/python3.9/site-packages/ray/tune/trial_runner.py", line 739, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/qc_whaley/anaconda3/envs/tf2.6/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py", line 746, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/qc_whaley/anaconda3/envs/tf2.6/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/qc_whaley/anaconda3/envs/tf2.6/lib/python3.9/site-packages/ray/worker.py", line 1623, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::UniTTN.__init__()[39m (pid=5188, ip=10.128.0.8)
  File "/home/qc_whaley/anaconda3/envs/tf2.6/lib/python3.9/site-packages/ray/tune/trainable.py", line 103, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/qc_whaley/dephased_ttn_project/uni_ttn/tf2.7/non_distributed_tunning/model.py", line 219, in setup
    self.model = Model(data_path, digits, val_split, deph_p, num_anc, config, tune_config)
  File "/home/qc_whaley/dephased_ttn_project/uni_ttn/tf2.7/non_distributed_tunning/model.py", line 92, in __init__
    train_data, val_data, test_data = data.get_data_file(
  File "/home/qc_whaley/dephased_ttn_project/uni_ttn/tf2.7/non_distributed_tunning/data.py", line 143, in get_data_file
    (train_raw_im, train_raw_lab) = load_data(data_path + '_train')
  File "/home/qc_whaley/dephased_ttn_project/uni_ttn/tf2.7/non_distributed_tunning/data.py", line 188, in load_data
    dest = open(path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/qc_whaley/dephased_ttn_project/mnist8by8_exp/mnist8by8_train'

